-- =====================================================================
-- Migração 004: planos, teste grátis e cobrança recorrente (Asaas).
-- Idempotente.
-- =====================================================================
SET search_path TO dbo, public;
SELECT set_config('app.sistema', 'on', true);

-- ---------- Assinatura de cada empresa cliente ----------
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS status_assinatura VARCHAR(20);   -- cortesia | teste | ativa | atrasada | cancelada
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS teste_ate TIMESTAMP;
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS atrasada_desde TIMESTAMP;
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS limite_clientes INT;             -- NULL = sem limite
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS cpf_cnpj VARCHAR(20);
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS email_cobranca CITEXT;
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS telefone VARCHAR(30);
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS asaas_customer_id VARCHAR(40);
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS asaas_subscription_id VARCHAR(40);
ALTER TABLE dbo.nps_contas ADD COLUMN IF NOT EXISTS origem VARCHAR(20) DEFAULT 'plataforma'; -- plataforma | cadastro

-- Contas que já existiam antes da cobrança continuam liberadas (cortesia).
UPDATE dbo.nps_contas SET status_assinatura = 'cortesia' WHERE status_assinatura IS NULL;
ALTER TABLE dbo.nps_contas ALTER COLUMN status_assinatura SET DEFAULT 'teste';

-- ---------- Histórico de cobranças ----------
CREATE TABLE IF NOT EXISTS dbo.nps_cobrancas (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id         INT NOT NULL REFERENCES dbo.nps_contas(id),
    asaas_payment_id VARCHAR(40) UNIQUE,
    valor            NUMERIC(10, 2),
    status           VARCHAR(40),
    forma            VARCHAR(20),
    vencimento       DATE,
    pago_em          DATE,
    link             TEXT,
    ultimo_evento    VARCHAR(60),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_cobrancas_conta ON dbo.nps_cobrancas (conta_id, vencimento DESC);
ALTER TABLE dbo.nps_cobrancas ENABLE ROW LEVEL SECURITY;
ALTER TABLE dbo.nps_cobrancas FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS isolamento_conta ON dbo.nps_cobrancas;
CREATE POLICY isolamento_conta ON dbo.nps_cobrancas
    USING (conta_id = dbo.conta_atual() OR dbo.modo_sistema())
    WITH CHECK (conta_id = dbo.conta_atual() OR dbo.modo_sistema());

-- ---------- Limite de clientes do plano (vale para qualquer tela ou importação) ----------
CREATE OR REPLACE FUNCTION dbo.verificar_limite_clientes() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    limite int;
    total  int;
BEGIN
    IF COALESCE(NEW.ativo, 1) <> 1 THEN
        RETURN NEW;
    END IF;
    -- edição de um contato que já estava ativo não conta como cliente novo
    IF TG_OP = 'UPDATE' AND COALESCE(OLD.ativo, 1) = 1 THEN
        RETURN NEW;
    END IF;
    SELECT limite_clientes INTO limite FROM dbo.nps_contas WHERE id = NEW.conta_id;
    IF limite IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT COUNT(*) INTO total FROM dbo.nps_clientes
     WHERE conta_id = NEW.conta_id AND COALESCE(ativo, 1) = 1
       AND (TG_OP = 'INSERT' OR cliente_id <> NEW.cliente_id);
    IF total >= limite THEN
        RAISE EXCEPTION 'Limite do plano atingido: até % clientes ativos. Mude de plano em Assinatura.', limite
            USING ERRCODE = 'P0001';
    END IF;
    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_limite_clientes ON dbo.nps_clientes;
CREATE TRIGGER trg_limite_clientes
    BEFORE INSERT OR UPDATE OF ativo ON dbo.nps_clientes
    FOR EACH ROW EXECUTE FUNCTION dbo.verificar_limite_clientes();
