-- =====================================================================
-- Migração 001: multiempresa (cada cliente da Rakiti é uma "conta")
-- Idempotente: pode ser executada mais de uma vez.
--
-- Isolamento feito pelo próprio PostgreSQL (Row Level Security):
-- toda consulta só enxerga as linhas da conta definida em app.conta_id.
-- A aplicação define essa variável a cada transação (database.py).
-- =====================================================================
SET search_path TO dbo, public;

-- ---------- Contas ----------
CREATE TABLE IF NOT EXISTS dbo.nps_contas (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(255) NOT NULL,
    webhook_token  VARCHAR(64) NOT NULL UNIQUE DEFAULT (md5(random()::text || clock_timestamp()::text) || md5(random()::text)),
    plano          VARCHAR(50) DEFAULT 'piloto',
    ativo          SMALLINT DEFAULT 1,
    criado_em      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO dbo.nps_contas (id, nome)
SELECT 1, 'Conta principal' WHERE NOT EXISTS (SELECT 1 FROM dbo.nps_contas);
SELECT setval(pg_get_serial_sequence('dbo.nps_contas', 'id'), GREATEST((SELECT MAX(id) FROM dbo.nps_contas), 1));

-- ---------- Funções de contexto ----------
CREATE OR REPLACE FUNCTION dbo.conta_atual() RETURNS int LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('app.conta_id', true), '')::int $$;
CREATE OR REPLACE FUNCTION dbo.modo_sistema() RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT COALESCE(current_setting('app.sistema', true), '') = 'on' $$;

-- ---------- conta_id em todas as tabelas + RLS ----------
DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'nps_companhias','nps_segmentos','nps_perfis','nps_cargos','nps_gestores',
        'nps_configuracoes','nps_configuracoes_email','nps_usuarios','nps_sessoes_ativas',
        'nps_permissoes','nps_logs','nps_empresas','nps_clientes','nps_respostas',
        'nps_acoes','nps_disparos'
    ] LOOP
        EXECUTE format('ALTER TABLE dbo.%I ADD COLUMN IF NOT EXISTS conta_id INT NOT NULL DEFAULT 1 REFERENCES dbo.nps_contas(id)', t);
        EXECUTE format('ALTER TABLE dbo.%I ALTER COLUMN conta_id SET DEFAULT dbo.conta_atual()', t);
        EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_conta ON dbo.%I (conta_id)', t, t);
        EXECUTE format('ALTER TABLE dbo.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE dbo.%I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS isolamento_conta ON dbo.%I', t);
        EXECUTE format('CREATE POLICY isolamento_conta ON dbo.%I USING (conta_id = dbo.conta_atual() OR dbo.modo_sistema()) WITH CHECK (conta_id = dbo.conta_atual() OR dbo.modo_sistema())', t);
    END LOOP;
END $$;

-- ---------- Chaves únicas passam a ser por conta ----------
ALTER TABLE dbo.nps_configuracoes DROP CONSTRAINT IF EXISTS nps_configuracoes_pkey;
ALTER TABLE dbo.nps_configuracoes ADD PRIMARY KEY (conta_id, chave);

ALTER TABLE dbo.nps_permissoes DROP CONSTRAINT IF EXISTS nps_permissoes_pkey;
ALTER TABLE dbo.nps_permissoes ADD PRIMARY KEY (conta_id, perfil, chave);

ALTER TABLE dbo.nps_clientes DROP CONSTRAINT IF EXISTS nps_clientes_email_key;
CREATE UNIQUE INDEX IF NOT EXISTS ux_clientes_conta_email ON dbo.nps_clientes (conta_id, email);

DROP INDEX IF EXISTS dbo.ux_respostas_submission;
CREATE UNIQUE INDEX IF NOT EXISTS ux_respostas_conta_submission ON dbo.nps_respostas (conta_id, submission_id)
    WHERE submission_id IS NOT NULL AND submission_id <> '';

CREATE UNIQUE INDEX IF NOT EXISTS ux_config_email_conta ON dbo.nps_configuracoes_email (conta_id);
-- e-mail de usuário continua único na plataforma inteira (identifica a conta no login)
