-- =====================================================================
-- Migração 003: construtor de formulários (vários formulários por conta,
-- perguntas de vários tipos, páginas, lógica por nota, tema e link público).
-- Idempotente.
-- =====================================================================
SET search_path TO dbo, public;
SELECT set_config('app.sistema', 'on', true);

CREATE TABLE IF NOT EXISTS dbo.nps_formularios (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id     INT NOT NULL DEFAULT dbo.conta_atual() REFERENCES dbo.nps_contas(id),
    nome         VARCHAR(150) NOT NULL,
    descricao    TEXT,
    perguntas    JSONB NOT NULL DEFAULT '[]'::jsonb,   -- lista de perguntas (ver services/formularios_svc.py)
    tema         JSONB NOT NULL DEFAULT '{}'::jsonb,   -- cor, logo, layout, mensagens
    codigo       VARCHAR(24),                          -- link público /f/{codigo}
    publico      SMALLINT NOT NULL DEFAULT 0,          -- 1 = aceita respostas pelo link público
    ativo        SMALLINT NOT NULL DEFAULT 1,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_formularios_codigo ON dbo.nps_formularios (codigo) WHERE codigo IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_formularios_conta ON dbo.nps_formularios (conta_id);
ALTER TABLE dbo.nps_formularios ENABLE ROW LEVEL SECURITY;
ALTER TABLE dbo.nps_formularios FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS isolamento_conta ON dbo.nps_formularios;
CREATE POLICY isolamento_conta ON dbo.nps_formularios
    USING (conta_id = dbo.conta_atual() OR dbo.modo_sistema())
    WITH CHECK (conta_id = dbo.conta_atual() OR dbo.modo_sistema());

-- Todas as respostas (todas as perguntas) de cada formulário
CREATE TABLE IF NOT EXISTS dbo.nps_formulario_respostas (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id       INT NOT NULL DEFAULT dbo.conta_atual() REFERENCES dbo.nps_contas(id),
    formulario_id  INT REFERENCES dbo.nps_formularios(id) ON DELETE CASCADE,
    disparo_id     INT REFERENCES dbo.nps_disparos(id) ON DELETE SET NULL,
    cliente_id     VARCHAR(50) REFERENCES dbo.nps_clientes(cliente_id) ON DELETE SET NULL,
    email          CITEXT,
    referencia     VARCHAR(255),
    nota_principal INT,
    respostas      JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {id_da_pergunta: valor}
    canal          VARCHAR(50) DEFAULT 'Formulário Rakiti',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_form_resp_form ON dbo.nps_formulario_respostas (conta_id, formulario_id, created_at);
ALTER TABLE dbo.nps_formulario_respostas ENABLE ROW LEVEL SECURITY;
ALTER TABLE dbo.nps_formulario_respostas FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS isolamento_conta ON dbo.nps_formulario_respostas;
CREATE POLICY isolamento_conta ON dbo.nps_formulario_respostas
    USING (conta_id = dbo.conta_atual() OR dbo.modo_sistema())
    WITH CHECK (conta_id = dbo.conta_atual() OR dbo.modo_sistema());

-- Qual formulário foi usado em cada convite
ALTER TABLE dbo.nps_disparos ADD COLUMN IF NOT EXISTS formulario_id INT REFERENCES dbo.nps_formularios(id) ON DELETE SET NULL;
