-- =====================================================================
-- Migração 002: formulário próprio de pesquisa (NPS e CSAT)
-- Idempotente.
-- =====================================================================
SET search_path TO dbo, public;
SELECT set_config('app.sistema', 'on', true);  -- migração enxerga todas as contas

-- Cada convite ganha um link único (token) para o formulário da Rakiti
ALTER TABLE dbo.nps_disparos ADD COLUMN IF NOT EXISTS token VARCHAR(64);
ALTER TABLE dbo.nps_disparos ADD COLUMN IF NOT EXISTS tipo_pesquisa VARCHAR(10) DEFAULT 'nps';   -- 'nps' | 'csat'
ALTER TABLE dbo.nps_disparos ADD COLUMN IF NOT EXISTS referencia VARCHAR(255);                    -- ex.: nº do pedido/entrega (CSAT)
ALTER TABLE dbo.nps_disparos ADD COLUMN IF NOT EXISTS assunto_pesquisa VARCHAR(255);              -- ex.: "a entrega do pedido 123"
ALTER TABLE dbo.nps_disparos ADD COLUMN IF NOT EXISTS respondido_em TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS ux_disparos_token ON dbo.nps_disparos (token) WHERE token IS NOT NULL;

-- Respostas de CSAT (satisfação de 1 a 5) ficam separadas das de NPS,
-- para não misturar as duas métricas nos painéis.
CREATE TABLE IF NOT EXISTS dbo.nps_csat_respostas (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id     INT NOT NULL DEFAULT dbo.conta_atual() REFERENCES dbo.nps_contas(id),
    disparo_id   INT REFERENCES dbo.nps_disparos(id) ON DELETE SET NULL,
    cliente_id   VARCHAR(50) REFERENCES dbo.nps_clientes(cliente_id) ON DELETE SET NULL,
    empresa_id   INT REFERENCES dbo.nps_empresas(id) ON DELETE SET NULL,
    email        CITEXT,
    nota         INT NOT NULL CHECK (nota BETWEEN 1 AND 5),
    comentario   TEXT,
    referencia   VARCHAR(255),
    assunto      VARCHAR(255),
    canal        VARCHAR(50) DEFAULT 'Formulário Rakiti',
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_csat_conta ON dbo.nps_csat_respostas (conta_id, created_at);
ALTER TABLE dbo.nps_csat_respostas ENABLE ROW LEVEL SECURITY;
ALTER TABLE dbo.nps_csat_respostas FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS isolamento_conta ON dbo.nps_csat_respostas;
CREATE POLICY isolamento_conta ON dbo.nps_csat_respostas
    USING (conta_id = dbo.conta_atual() OR dbo.modo_sistema())
    WITH CHECK (conta_id = dbo.conta_atual() OR dbo.modo_sistema());

-- Contas que já usavam um formulário externo (Fillout) continuam com ele
INSERT INTO dbo.nps_configuracoes (conta_id, chave, valor, descricao)
SELECT c.conta_id, 'formulario_tipo', 'externo', 'proprio = formulário da Rakiti | externo = link próprio (ex.: Fillout)'
FROM dbo.nps_configuracoes c
WHERE c.chave = 'survey_url' AND c.valor LIKE 'https://%'
ON CONFLICT (conta_id, chave) DO NOTHING;
