-- =====================================================================
-- NPS - Schema PostgreSQL (convertido do script original + ajustes)
-- Rodar uma única vez num banco vazio:  psql "$DATABASE_URL" -f db/schema_postgres.sql
--
-- Decisões para minimizar mudanças no código atual:
--  * Tabelas no schema "dbo"  -> as consultas "dbo.nps_..." continuam válidas.
--  * Flags como SMALLINT 0/1  -> o código compara "ativo = 1"; BOOLEAN quebraria isso.
--  * Colunas que o código usa mas faltavam no script foram adicionadas (marcadas com [NOVO]).
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS dbo;
SET search_path TO dbo, public;
CREATE EXTENSION IF NOT EXISTS citext;   -- e-mails e nomes sem diferenciar maiúsculas (como no SQL Server)

-- ---------- Funções de compatibilidade com o SQL Server ----------
-- Permitem que as consultas existentes (GETDATE, DATEADD, DATEDIFF...) rodem sem reescrita.
CREATE OR REPLACE FUNCTION dbo.getdate() RETURNS timestamp LANGUAGE sql STABLE AS $$ SELECT (now() AT TIME ZONE 'UTC') $$;
CREATE OR REPLACE FUNCTION dbo.getutcdate() RETURNS timestamp LANGUAGE sql STABLE AS $$ SELECT (now() AT TIME ZONE 'UTC') $$;
CREATE OR REPLACE FUNCTION dbo.sysutcdatetime() RETURNS timestamp LANGUAGE sql STABLE AS $$ SELECT (now() AT TIME ZONE 'UTC') $$;
CREATE OR REPLACE FUNCTION dbo.year(d timestamp) RETURNS int LANGUAGE sql IMMUTABLE AS $$ SELECT EXTRACT(YEAR FROM d)::int $$;
CREATE OR REPLACE FUNCTION dbo.month(d timestamp) RETURNS int LANGUAGE sql IMMUTABLE AS $$ SELECT EXTRACT(MONTH FROM d)::int $$;
CREATE OR REPLACE FUNCTION dbo.try_int(v text) RETURNS int LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE WHEN btrim(v) ~ '^-?[0-9]+$' THEN btrim(v)::int END $$;
CREATE OR REPLACE FUNCTION dbo.dateadd(unidade text, n numeric, d timestamp) RETURNS timestamp LANGUAGE sql IMMUTABLE AS $$
    SELECT d + (n::text || ' ' || CASE lower(unidade)
        WHEN 'd' THEN 'day' WHEN 'dd' THEN 'day' WHEN 'hh' THEN 'hour' WHEN 'mi' THEN 'minute'
        WHEN 'mm' THEN 'month' WHEN 'yy' THEN 'year' WHEN 'wk' THEN 'week' WHEN 'ss' THEN 'second'
        ELSE lower(unidade) END)::interval $$;
-- DATEDIFF conta "fronteiras" como no SQL Server (ex.: 23:59 -> 00:01 = 1 dia)
CREATE OR REPLACE FUNCTION dbo.datediff(unidade text, a timestamp, b timestamp) RETURNS int LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE lower(unidade)
        WHEN 'day' THEN (b::date - a::date)
        WHEN 'd' THEN (b::date - a::date)
        WHEN 'dd' THEN (b::date - a::date)
        WHEN 'hour' THEN floor(EXTRACT(EPOCH FROM (date_trunc('hour', b) - date_trunc('hour', a))) / 3600)::int
        WHEN 'minute' THEN floor(EXTRACT(EPOCH FROM (date_trunc('minute', b) - date_trunc('minute', a))) / 60)::int
        WHEN 'second' THEN floor(EXTRACT(EPOCH FROM (date_trunc('second', b) - date_trunc('second', a))))::int
        WHEN 'week' THEN ((b::date - a::date) / 7)
        WHEN 'month' THEN ((EXTRACT(YEAR FROM b) - EXTRACT(YEAR FROM a)) * 12 + EXTRACT(MONTH FROM b) - EXTRACT(MONTH FROM a))::int
        WHEN 'year' THEN (EXTRACT(YEAR FROM b) - EXTRACT(YEAR FROM a))::int
    END $$;

-- ---------- Cadastros básicos ----------
CREATE TABLE dbo.nps_companhias (
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  CITEXT       NOT NULL
);

CREATE TABLE dbo.nps_segmentos (
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  CITEXT       NOT NULL
);

CREATE TABLE dbo.nps_perfis (
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  CITEXT       NOT NULL
);

CREATE TABLE dbo.nps_cargos (
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  CITEXT       NOT NULL
);

CREATE TABLE dbo.nps_gestores (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           CITEXT       NOT NULL,
    papel          VARCHAR(100),
    email          CITEXT      ,
    teams_webhook  TEXT,
    avatar         TEXT
);

-- ---------- Configuração ----------
CREATE TABLE dbo.nps_configuracoes (
    chave       VARCHAR(100) PRIMARY KEY,
    valor       TEXT,
    descricao   VARCHAR(255),
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dbo.nps_configuracoes_email (
    tenant_id          VARCHAR(255),
    client_id          VARCHAR(255),
    client_secret      TEXT,
    email_remetente    VARCHAR(255),
    base_url_frontend  VARCHAR(255),
    refresh_token      TEXT,
    atualizado_em      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------- Usuários e segurança ----------
CREATE TABLE dbo.nps_usuarios (
    usuario_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(255) NOT NULL,
    email             CITEXT       UNIQUE NOT NULL,
    senha_hash        VARCHAR(255) NOT NULL,
    cargo             VARCHAR(100),
    tipo              VARCHAR(50),              -- 'Admin' | 'Manager' | 'Viewer' | 'Usuário'
    ativo             SMALLINT DEFAULT 1,
    avatar_url        TEXT,
    email_verificado  SMALLINT DEFAULT 1,
    ultimo_acesso     TIMESTAMP
);

CREATE TABLE dbo.nps_sessoes_ativas (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id        INT REFERENCES dbo.nps_usuarios(usuario_id) ON DELETE CASCADE,
    token_id          VARCHAR(255),
    dispositivo       TEXT,
    ip_address        VARCHAR(50),
    localizacao       VARCHAR(255),
    criado_em         TIMESTAMP,
    ultima_atividade  TIMESTAMP,
    revogado          SMALLINT DEFAULT 0
);
CREATE INDEX ix_sessoes_token ON dbo.nps_sessoes_ativas (token_id);

CREATE TABLE dbo.nps_permissoes (
    perfil  VARCHAR(100),
    chave   VARCHAR(100),
    PRIMARY KEY (perfil, chave)
);

CREATE TABLE dbo.nps_logs (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel         VARCHAR(50),
    acao          VARCHAR(100),
    mensagem      TEXT,
    usuario_id    INT REFERENCES dbo.nps_usuarios(usuario_id) ON DELETE SET NULL,
    data_criacao  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------- Carteira ----------
CREATE TABLE dbo.nps_empresas (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            CITEXT       NOT NULL,
    segmento        VARCHAR(100),
    valor_contrato  NUMERIC(18,2),
    gestor          VARCHAR(255),
    gestor_id       INT REFERENCES dbo.nps_gestores(id),
    companhia       VARCHAR(255),
    companhia_id    INT REFERENCES dbo.nps_companhias(id),
    ativo           SMALLINT DEFAULT 1,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dbo.nps_clientes (
    cliente_id    VARCHAR(50) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    nome          VARCHAR(255),
    email         CITEXT       UNIQUE NOT NULL,
    telefone      VARCHAR(50),
    empresa       VARCHAR(255),
    empresa_id    INT REFERENCES dbo.nps_empresas(id),
    perfil_id     INT REFERENCES dbo.nps_perfis(id),
    segmento_id   INT REFERENCES dbo.nps_segmentos(id),
    cargo_id      INT REFERENCES dbo.nps_cargos(id),
    cargo         VARCHAR(100),
    gestor        VARCHAR(255),
    ativo         SMALLINT DEFAULT 1,
    ultimo_envio  TIMESTAMP,
    proximo_envio DATE,                         -- [NOVO] usado no agendador de envios
    status_envio  VARCHAR(50),
    ultimo_erro   TEXT,                         -- [NOVO] usado no agendador de envios
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_clientes_empresa ON dbo.nps_clientes (empresa_id);
CREATE INDEX ix_clientes_envio   ON dbo.nps_clientes (status_envio, proximo_envio);

-- ---------- Respostas e ações ----------
CREATE TABLE dbo.nps_respostas (
    resposta_id     VARCHAR(50) PRIMARY KEY,
    cliente_id      VARCHAR(50) REFERENCES dbo.nps_clientes(cliente_id),
    email           CITEXT,                     -- [NOVO] gravado pelo webhook do Fillout
    empresa         VARCHAR(255),
    empresa_id      INT REFERENCES dbo.nps_empresas(id),
    perfil_decisor  VARCHAR(255),               -- [NOVO] usado na listagem/filtro de respostas
    nota            INT NOT NULL CHECK (nota BETWEEN 0 AND 10),
    motivo          TEXT,
    categoria       VARCHAR(100),
    canal           VARCHAR(100),
    expectativas    TEXT,
    o_que_faltava   TEXT,
    form_id         VARCHAR(100),               -- [NOVO] webhook do Fillout
    submission_id   VARCHAR(100),               -- [NOVO] evita respostas duplicadas
    data_resposta   TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    excluido        SMALLINT DEFAULT 0,
    jira_issue_url  VARCHAR(255)
);
CREATE INDEX ix_respostas_cliente ON dbo.nps_respostas (cliente_id);
CREATE INDEX ix_respostas_empresa ON dbo.nps_respostas (empresa_id);
CREATE INDEX ix_respostas_data    ON dbo.nps_respostas (data_resposta);
CREATE UNIQUE INDEX ux_respostas_submission ON dbo.nps_respostas (submission_id) WHERE submission_id IS NOT NULL AND submission_id <> '';

CREATE TABLE dbo.nps_acoes (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resposta_id   VARCHAR(50) REFERENCES dbo.nps_respostas(resposta_id),
    empresa_id    INT REFERENCES dbo.nps_empresas(id),
    gestor_id     INT REFERENCES dbo.nps_gestores(id),
    titulo        VARCHAR(255),
    descricao     TEXT,
    resolucao     TEXT,
    prioridade    VARCHAR(50),
    status        VARCHAR(50),
    prazo_limite  TIMESTAMP,
    data_criacao  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dbo.nps_disparos (
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id            VARCHAR(50) REFERENCES dbo.nps_clientes(cliente_id),
    empresa_id            INT REFERENCES dbo.nps_empresas(id),   -- [NOVO]
    nome                  VARCHAR(255),
    email                 CITEXT      ,
    assunto               VARCHAR(255),
    survey_url            TEXT,
    status                VARCHAR(50),
    erro_msg              TEXT,
    lembretes_enviados    INT DEFAULT 0,        -- [NOVO]
    data_envio_inicial    TIMESTAMP,
    data_ultimo_lembrete  TIMESTAMP,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_disparos_cliente ON dbo.nps_disparos (cliente_id);

-- =====================================================================
-- Configurações iniciais (ajuste os valores)
-- =====================================================================
INSERT INTO dbo.nps_configuracoes (chave, valor, descricao) VALUES
  ('dominios_permitidos',      'seudominio.com.br', 'Domínios de e-mail que podem acessar (separados por vírgula)'),
  ('url_sistema',              'https://nps-frontend.onrender.com', 'URL pública do frontend'),
  ('recorrencia_dias',         '90',  'Intervalo entre pesquisas para o mesmo cliente'),
  ('envios_ativos',            '0',   'Liga/desliga o disparo automático de pesquisas'),
  ('robo_ativo',               '0',   'Liga/desliga o agendador'),
  ('sessao_expiracao_minutos', '480', 'Tempo de sessão do usuário'),
  ('mostrar_sem_cliente',      '0',   'Mostrar respostas sem cliente vinculado'),
  ('sso_microsoft_ativo',      '0',   'Login com Microsoft'),
  ('sla_detrator_dias',        '2',   'SLA de tratamento de detratores'),
  ('sla_neutro_dias',          '5',   'SLA de tratamento de neutros'),
  ('sla_promotor_dias',        '10',  'SLA de tratamento de promotores'),
  ('openai_model',             'gpt-4o-mini', 'Modelo de IA'),
  ('ai_temperature',           '0.3', 'Criatividade da IA')
ON CONFLICT (chave) DO NOTHING;

-- Usuário administrador inicial:
--   1) gere o hash com:  python gerar_senha.py
--   2) troque os valores abaixo e descomente
-- INSERT INTO dbo.nps_usuarios (nome, email, senha_hash, tipo, cargo, ativo, email_verificado)
-- VALUES ('Marcelo Mendes', 'voce@seudominio.com.br', '<HASH_BCRYPT>', 'Admin', 'Administrador', 1, 1);
